---
- name: include the snapshot_keyspace yaml file per node
  include_vars:
    file: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_src_environment }}/{{ cassandra22x_src_cluster_node }}/{{ snapshot_keyspace_yml }}"

- import_tasks: rsync_hardlink_column_families_disk_to_column_families_disk.yml
- import_tasks: reset_permissions_column_families_disk.yml