---
- name: "create {{ cassandra22x_local_archive_path }}/{{ keyspace_name }}"
  file:
    path: "{{ cassandra22x_local_archive_path }}/{{ keyspace_name }}"
    state: directory
    mode: "{{ cassandra22x_linux_default_mode }}"

- name: "create {{ cassandra22x_local_archive_path_archived_logs }}"
  file:
    path: "{{ cassandra22x_local_archive_path_archived_logs }}"
    state: directory
    mode: "{{ cassandra22x_linux_default_mode }}"
    
- name: "create {{ cassandra22x_local_archive_path_archived_ansible_restore_vars }}"
  file:
    path: "{{ cassandra22x_local_archive_path_archived_ansible_restore_vars }}"
    state: directory
    mode: "{{ cassandra22x_linux_default_mode }}"
  delegate_to: 127.0.0.1