--- 
- name: include the snapshot_keyspace yaml file per node
  include_vars:
    file: "{{ restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ snapshot_keyspace_yml }}"

- import_tasks: rsync_local_snapshots_for_keyspace.yml