---
- name: "nodetool clearsnapshot -t {{ snapshot_name}} {{ keyspace_name }}"
  script: nodetool-clearsnapshot.sh {{ cassandra22x_ansible_superuser }} {{ cassandra22x_ansible_superuser_password }} {{ snapshot_name }} {{ keyspace_name }}