---
- name: "find snapshot_ymls {{ restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
  find:
    paths: "{{ restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
    patterns: 'snapshot_[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}.yml'
    use_regex: yes
  register: found_snapshot_yml
  no_log: true    


- name: "nodetool clearsnapshot -t {{ snapshot_name}} {{ keyspace_name }}"
  script: nodetool-clearsnapshot.sh {{ cassandra22x_ansible_superuser }} {{ cassandra22x_ansible_superuser_password }} {{ snapshot_name }} {{ keyspace_name }}