---
- name: "rsync snapshot ansible metadata from {{ restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/ to {{ cassandra22x_remote_archive_path_archived_ansible_restore_vars }}"
  synchronize:
    src: "{{ restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/"
    dest: "{{ cassandra22x_remote_archive_path_archived_ansible_restore_vars }}"
    rsync_opts:
        - "--bwlimit={{ rsync_bwlimit }}"
        - "--no-motd"
        - "--include=snapshot_*.tar.gz"
        - "--include=snapshot_*.tar"        
        - "--exclude=*"
  delegate_to: 127.0.0.1 