---
# pwd = /etc/ansible
# ansible-playbook playbooks/clusterx/cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_unarchive_new_schema_for_keyspace.yml -e"snapshot_keyspace_yml=snapshot_keyspace_yml"

- hosts: cassx.deltakappa.com
  any_errors_fatal: true
   
  pre_tasks:
    - name: capture playbook start time
      set_fact: 
        start_date_time_fact: "{{ now }}"  

    - name: loop cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_unarchive_new_schema_for_keyspace role for each cassandra22x_node_idx.cassandra22x_src_cluster_node_map_dict
      include_role:
        name: cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_unarchive_new_schema_for_keyspace
      loop: "{{ cassandra22x_src_cluster_node_map_dict }}"
      loop_control:
        loop_var: cassandra22x_node_idx
        
  roles:
    - cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_for_keyspace_schema
    - cassandra22x_restore_src_dest_cluster_snapshot_local_unarchive_keyspace_schema
    - cassandra22x_restore_src_dest_cluster_snapshot_new_schema_for_keyspace

  post_tasks:
    - name: capture playbook end time
      set_fact: 
        end_date_time_fact: "{{ now }}"
        
    - name: cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_unarchive_new_schema_for_keyspace.yml play start and end date times
      debug: 
        msg: "start_date_time: {{ start_date_time_fact }} & end_date_time: {{ end_date_time_fact }}"