---
# pwd = /etc/ansible
# ansible-playbook playbooks/clusterx/cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_unarchive_new_schema_sstableload_data_for_keyspace.yml -e"snapshot_keyspace_yml=snapshot_keyspace_yml"

- hosts: clusterx
  max_fail_percentage: 0
  serial: 1
  # gather_facts: no
   
  pre_tasks:
    - name: capture playbook start time
      set_fact: 
        start_date_time_fact: "{{ now }}"  

  roles:
    - cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_unarchive_new_schema_sstableload_data_for_keyspace

  post_tasks:
    - name: capture playbook end time
      set_fact: 
        end_date_time_fact: "{{ now }}"
        
    - name: cassandra22x_restore_src_dest_cluster_snapshot_remote_local_rsync_unarchive_new_schema_sstableload_data_for_keyspace.yml play start and end date times
      debug: 
        msg: "start_date_time: {{ start_date_time_fact }} & end_date_time: {{ end_date_time_fact }}"