---
# pwd = /etc/ansible
# ansible-playbook playbooks/clusterx/cassandra22x_restore_src_dest_cluster_snapshot_clean_up.yml -e"snapshot_yml=snapshot_yml"

- hosts: clusterx
  max_fail_percentage: 0
  serial: 1
  # gather_facts: no
   
  pre_tasks:
    - name: capture playbook start time
      set_fact: 
        start_date_time_fact: "{{ now }}"
        
    - name: "loop cassandra22x_restore_src_dest_cluster_get_node_map_dict role for just the {{ cassandra22x_dest_cluster_node_schema }}"
      include_role:
        name: cassandra22x_restore_src_dest_cluster_get_node_map_dict
      loop: "{{ cassandra22x_src_cluster_node_map_dict }}"
      loop_control:
        loop_var: cassandra22x_node_idx

  roles:
    - cassandra22x_restore_src_dest_cluster_snapshot_clean_up

  post_tasks:
    - name: capture playbook end time
      set_fact: 
        end_date_time_fact: "{{ now }}"
        
    - name: cassandra22x_restore_src_dest_cluster_snapshot_clean_up.yml play start and end date times
      debug: 
        msg: "start_date_time: {{ start_date_time_fact }} & end_date_time: {{ end_date_time_fact }}"