---
# pwd = /etc/ansible
# ansible-playbook playbooks/clusterx/cassandra22x_restore_src_dest_cluster_snapshot_remote_local_diff_topology.yml -e"snapshot_keyspace_yml=snapshot_keyspace_yml"

- hosts: clusterx
  any_errors_fatal: true
    
  tasks:
  
  
    - include_role: 
        name: cassandra22x_restore_src_dest_cluster_snapshot_remote_local_diff_topology      
      loop: "{{ cassandra22x_src_cluster_node_map_dict }}"
      loop_control:
        loop_var: cassandra22x_node_idx