---
### Descriptioin: archive_snapshot.yml for the cass_snapshot role
### Author: David Payne
### 
### CQGiki documentation: http://cqgiki.denver.cqg/bin/view/Production/CassandraOps

- name: gz archive C* snapshot log, cql, yml, and tar files
  archive:
    path: "{{ cass_log_path }}/{{ fact_snapshot_name }}*.*"
    dest: "{{ cass_log_path }}/{{ fact_snapshot_name }}.gz"
    format: gz    
    remove: True