---
### Descriptioin: snapshot.yml task for the cass_snapshot role
### Author: David Payne
### 
### CQGiki documentation: http://cqgiki.denver.cqg/bin/view/Production/CassandraOps

- name: create missing archive directories for each keyspace
  file:
    path: "{{ cass_local_archive_root }}/{{ item }}/snapshots"
    state: directory
    owner: cassandra
    group: cassandra
    mode: "u=rwx,g=rx,o=rx"
  with_items: "{{ fact_snapshot_keyspace_list }}"

- name: gz archive snapshots for each keyspace in the local keyspace archive directory
  archive:
    path: "{{ cass_data_path }}/{{ item }}/*/snapshots/{{ fact_snapshot_name }}"
    dest: "{{ cass_local_archive_root }}/{{ item }}/snapshots/{{ fact_snapshot_name }}.gz"
    format: gz
  with_items: "{{ fact_snapshot_keyspace_list }}"

- name: gz archive C* snapshot cass_log_path files
  archive:
    path: "{{ cass_log_path }}/{{ fact_snapshot_name }}*.*"
    dest: "{{ cass_log_path }}/{{ fact_snapshot_name }}.gz"
    format: gz    
    remove: True