---
- name: "create missing vars paths - {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
  file:
    path: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
    state: directory
  delegate_to: 127.0.0.1
        
- name: "rsync metadata (yaml files) created to the ansible system"
  synchronize:
    mode: pull
    src: "{{ cassandra22x_log_path }}/"
    dest: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}"
    rsync_opts:
        - "--no-motd"
        - "--include=*.yml"
        - "--exclude=*"