---
- name: "nodetool snapshot {{ fact_snapshot_name }} keyspace"
  script: nodetool-snapshot.sh {{ cassandra22x_remote_jmx_user }} {{ cassandra22x_remote_jmx_pass }} {{ fact_snapshot_name }} {{ item }} {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}_{{ item }}.log
  with_items: "{{ fact_snapshot_keyspace_list }}"