---
- name: "loop create_schema_cql_for_keyspace.yml for each keyspace on the cassandra node"
  include_tasks: create_schema_cql_for_keyspace.yml
  loop: "{{ fact_snapshot_keyspace_list }}"
  loop_control:
    loop_var: keyspace_name