---
- name: "create missing {{ cassandra22x_local_archive_path_for_src_environment_cluster_node }}/{{ keyspace_name }}/snapshots"
  file:
    path: "{{ cassandra22x_local_archive_path_for_src_environment_cluster_node }}/{{ keyspace_name }}/snapshots"
    state: directory
    owner: root
    group: root    
    mode: "{{ cassandra22x_root_default_directory_mode }}"