snapshot_name: snapshot_c56ee4af-f296-45a7-8e1e-9024f2a5ad8b
keyspace_name: system_distributed
column_families:
    - parent_repair_history
    - repair_history

column_families_disk:
    - parent_repair_history-deabd734b99d3b9c92e5fd92eb5abf14
    - repair_history-759fffad624b318180eefa9a52d1f627

