snapshot_name: snapshot_2fe6bd4a-7734-4982-b6af-af06e02c539e
keyspace_name: system_auth
column_families:
    - resource_role_permissons_index
    - role_members
    - role_permissions
    - roles

column_families_disk:
    - resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec
    - role_members-0ecdaa87f8fb3e6088d174fb36fe5c0d
    - role_permissions-3afbe79f219431a7add7f5ab90d8ec9c
    - roles-5bc52802de2535edaeab188eecebb090

