---
- name: loop role for each cassandra22x_node_idx.cassandra22x_src_cluster_node_map_dict
  include_role:
    name: cassandra22x_restore_src_dest_cluster_snapshot
  loop: "{{ cassandra22x_src_cluster_node_map_dict }}"
  loop_control:
    loop_var: cassandra22x_node_idx