---
# pwd = /etc/ansible
# ansible-playbook playbooks/cluster220/cassandra22x_operate_start.yml

- hosts: cluster220
  any_errors_fatal: true
  # max_fail_percentage: 0
  serial: 1
  gather_facts: no
  
  pre_tasks:
    - name: capture playbook start time
      set_fact: 
        start_date_time_fact: "{{ now }}"  

  roles:
     - cassandra22x_operate_start
     
  post_tasks:
    - name: capture playbook end time
      set_fact: 
        end_date_time_fact: "{{ now }}"
        
    - name: cassandra22x_operate_start.yml play start and end date times
      debug: 
        msg: "start_date_time: {{ start_date_time_fact }} & end_date_time: {{ end_date_time_fact }}"