---
- name: create missing archive directories for each keyspace
  file:
    path: "{{ cassandra22x_local_archive_path }}/{{ item }}/snapshots"
    state: directory
    owner: cassandra
    group: cassandra
    mode: "u=rwx,g=rx,o=rx"
  with_items: "{{ fact_snapshot_keyspace_list }}"
 
- name: "tar snapshot {{ cassandra22x_data_path }}/keyspaces/*/snapshots/{{ fact_snapshot_name }} into {{ cassandra22x_local_archive_path }}/{{ fact_snapshot_name }}.tar"
  archive:
    path: "{{ cassandra22x_data_path }}/{{ item }}/*/snapshots/{{ fact_snapshot_name }}"
    dest: "{{ cassandra22x_local_archive_path }}/{{ item }}/snapshots/{{ fact_snapshot_name }}.tar"
    format: tar
  with_items: "{{ fact_snapshot_keyspace_list }}"

- name: "create {{ cassandra22x_local_archive_path_archived_logs }}"
  file:
    path: "{{ cassandra22x_local_archive_path_archived_logs }}
    state: directory
    owner: cassandra
    group: cassandra
    mode: "u=rwx,g=rx,o=rx"
  
- name: "tar snapshot {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}*.* into {{ cassandra22x_local_archive_path }}/{{ fact_snapshot_name }}.tar"
  archive:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}*.*"
    dest: "{{ cassandra22x_local_archive_path_archived_logs }}/{{ fact_snapshot_name }}.tar"
    format: tar

- name: "tar snapshot {{ restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ fact_snapshot_name }}*.yml into {{ cassandra22x_local_archive_path_archived_logs }}/{{ fact_snapshot_name }}.tar"
  archive:
    path: "{{ restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ fact_snapshot_name }}*.yml"
    dest: "{{ cassandra22x_local_archive_path_archived_logs }}/{{ fact_snapshot_name }}.tar"
    format: tar
  delegate_to: 127.0.0.1