---
- name: "{{ cassandra22x_local_archive_format }} snapshot {{ cassandra22x_data_path }}/keyspaces/*/snapshots/{{ fact_snapshot_name }} into {{ cassandra22x_local_archive_path }}/{{ fact_snapshot_name }}{{ cassandra22x_local_archive_file_ext }}"
  archive:
    path: "{{ cassandra22x_data_path }}/{{ item }}/*/snapshots/{{ fact_snapshot_name }}"
    dest: "{{ cassandra22x_local_archive_path }}/{{ item }}/snapshots/{{ fact_snapshot_name }}{{ cassandra22x_local_archive_file_ext }}"
    format: "{{ cassandra22x_local_archive_format }}"
  with_items: "{{ fact_snapshot_keyspace_list }}"
  
- name: "{ cassandra22x_local_archive_format }} snapshot {{ cassandra22x_log_path }}/{{ fact_snapshot_name }}*.* into {{ cassandra22x_local_archive_path }}/{{ fact_snapshot_name }}{{ cassandra22x_local_archive_file_ext }}"
  archive:
    path: "{{ cassandra22x_log_path }}/{{ fact_snapshot_name }}*.*"
    dest: "{{ cassandra22x_local_archive_path_archived_logs }}/{{ fact_snapshot_name }}{{ cassandra22x_local_archive_file_ext }}"
    format: "{{ cassandra22x_local_archive_format }}"

- name: "{ cassandra22x_local_archive_format }} snapshot {{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ fact_snapshot_name }}*.yml into {{ cassandra22x_local_archive_path_archived_logs }}/{{ fact_snapshot_name }}{{ cassandra22x_local_archive_file_ext }}"
  archive:
    path: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ fact_snapshot_name }}*.yml"
    dest: "{{ cassandra22x_restore_vars }}/{{ cassandra22x_environment }}/{{ inventory_hostname }}/{{ fact_snapshot_name }}{{ cassandra22x_local_archive_file_ext }}"
    format: "{{ cassandra22x_local_archive_format }}"
  delegate_to: 127.0.0.1